server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BAStriver/springcloud-test-config.git #Github上的git仓库名字
          ##搜索目录.这个目录指的是github上的目录 https://github.com/BAStriver/springcloud-test-config.git
          search-paths:
            - config-repo
      ##读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/


